# Changes here will be overwritten by Copier
_commit: v1.4.6
_src_path: gh:lincc-frameworks/python-project-template
author_email: m.schwamb@qub.ac.uk
author_name: Adler Team
create_example_module: false
custom_install: true
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: adler
preferred_linter: black
project_license: none
project_name: adler
project_organization: lsst-uk
use_isort: false
